first

diff --git a/bibliohack b/bibliohack
--- a/bibliohack
+++ b/bibliohack
@@ -1,16 +1,5 @@
 #!/bin/bash
 
-case $(tty) in 
- /dev/tty[0-9]*)
-   echo "Verificando terminal: OK" 
-   ;;
- *)
-   echo "Este script debe ejecutarse desde una terminal virtual," 
-   echo "no dentro de un emulador de terminal en una sesion grafica."
-   echo "Use Ctrl + Alt + una tecla de función, por ejemplo Ctrl + Alt + F3"
-   echo "Luego ingrese su usuario/contraseña de linux"
-esac
-
 OSNAME=`lsb_release -is`
 CODENM=`lsb_release -cs`
 RELEASN=`lsb_release -rs`
@@ -20,33 +9,24 @@ if [ "$RELEASN" == '18.04' ] && [ "$OSNAME" == 'Ubuntu' ]
    echo "Instalando en: $OSNAME $RELEASN $CODENM"
 else
    echo "Este script es para instalar Bibliohack en Ubuntu 18.04"
+   exit 1
 fi
 
 OWN_PATH="$PWD/$0"
 CURRENT_USER="$USER"
+ARCH="$(uname -m)"
 
-[[ "$1" == "" ]] && SRCDIR=/opt/src || SRCDIR="$1"
+SRCDIR="/opt/src"
 
-[[ -d "$SRCDIR" ]] || { 
-   sudo mkdir "$SRCDIR" || {
-      [[ -d "$(dirname "$SRCDIR")" ]] && \
-         echo "error: no se pudo crear '$SRCDIR' porque no existe " ||\
-         echo "verifique que la carpeta padre exista"
-      exit 1
-   } 
-}
+if [[ ! -d "/opt" ]]; then
+  sudo mkdir "/opt" || { echo "error!"; exit 1;}
+fi
 
-sudo chmod a+rw "$SRCDIR" && exit 0 || { echo "error!"; exit 1; }
+if [[ ! -d "$SRCDIR" ]]; then 
+  sudo mkdir "$SRCDIR" || { echo "error!"; exit 1;}
+fi
 
-# instalacion de entorno de escritorio
-
-sudo /etc/init.d/gdm3 stop || { echo "No se pudo cerrar el entorno de escritorio"; exit 1; }
-sudo apt-get -y install gnome-session-flashback || { echo "error!"; exit 1; }
-sudo apt-get remove ubuntu-session || { echo "error!"; exit 1; }
-sudo apt-get install telegram-desktop
-
-sudo apt-get -y install curl xclip && cd /usr/bin && curl https://getmic.ro | sudo bash
-cd
+sudo chmod a+rw "$SRCDIR" || { echo "error!"; exit 1; }
 
 # instaladores
 
@@ -54,8 +34,8 @@ sudo apt-get -y install git subversion || { echo "error!"; exit 1; }
 if [[ -d "$SRCDIR/instaladores" ]] 
  then 
   echo "Instaladores ya está instalado en '/opt/src/instaladores'!"
-  cd "$SRCDIR"/instaladores || exit 1
-  git pull || exit 1
+  # cd "$SRCDIR"/instaladores
+  # git pull || exit 1
 else
   git clone http://github.com/d-a-l/instaladores.git "$SRCDIR"/instaladores || exit 1
 fi
@@ -74,7 +54,7 @@ cd "$SRCDIR"/instaladores || {
   echo "es ese caso use cada script de instaladores para agregar o quitar componentes."
   exit 1
 }
-[[ -d "$SRCDIR/scantailor-enhanced" ]] && { 
+[[ -d "$SRCDIR/scantailor-advanced" ]] && { 
   echo "Scantailor está instalado en '/opt/src/scantailor-enhanced'"
   echo "No use este script si ya existe una instalción previa,"
   echo "es ese caso use cada script de instaladores para agregar o quitar componentes."
@@ -96,20 +76,24 @@ if [ "$check_iup_ver" != "" ]
   exit 1
 fi
 
+cd "$SRCDIR/instaladores"
+
 # tecgraf
-"$SRCDIR"/instaladores/tecgraf install profile=d || { echo "error!"; exit 1; }
+./tecgraf install profile=d || { echo "error!"; exit 1; }
 
 # chdkptp
-"$SRCDIR"/instaladores/chdkptp install profile=d || { echo "error!"; exit 1; }
+./chdkptp install profile=d || { echo "error!"; exit 1; }
 
 # Scantailor
-sudo "$SRCDIR"/instaladores/scantailor-enhanced || { echo "error!"; exit 1; }
+sudo ./scantailor-advanced || { echo "error!"; exit 1; }
+
+
 
 # PDFBeads-kopi
+cd  "$SRCDIR"
 sudo apt-get -y install ruby-full ruby-dev rubygems || { echo "error!"; exit 1; }
-sudo apt-get -y install ruby-rmagick ruby-hpricot || { echo "error!"; exit 1; }
+sudo apt-get -y install ruby-nokogiri ruby-rmagick ruby-hpricot || { echo "error!"; exit 1; }
 sudo gem install iconv || { echo "error!"; exit 1; }
-sudo gem install nokogiri || { echo "error!"; exit 1; }
 
 git clone http://github.com/d-a-l/pdfbeads-kopi.git "$SRCDIR"/pdfbeads-kopi || exit 1
 
@@ -141,5 +125,10 @@ git checkout singlecam || exit 1
 git clone http://github.com/d-a-l/fcen-tesis.git "$SRCDIR"/fcen-tesis || exit 1
 
 # 
+cd "$SRCDIR/instaladores"
+./chdkptp_avoid_interactions || echo "error! chdkptp and gphoto2!"
 
-"$SRCDIR"/instaladores/chdkptp_avoid_interactions || echo "error! chdkptp and gphoto2!"
+# if [ "$RELOAD_GDM3" == "Si" ]
+#    sudo /etc/init.d/gdm3 restart || { echo "No se pudo cerrar el entorno de escritorio"; exit 1; }
+#  then
+# fi
diff --git a/chdkptp b/chdkptp
--- a/chdkptp
+++ b/chdkptp
@@ -7,9 +7,9 @@
 
 function set_chdkptp_profile {
 
-    if [[ "$1" =~ ^profile=[d|u]*$ ]]
+    if [[ "$1" =~ "d"|"u" ]]
      then
-       profile="${1#*=}"
+       profile="$1"
        echo "perfil de intalacion: '$profile'"
     else
       echo "Seleccione el perfil de instalación para CHDKPTP:"
@@ -44,13 +44,24 @@ function set_chdkptp_profile {
       CD_VER="5.6.1"
       IM_VER="3.8.2"
     else
-      echo "ERROR: profile = '$profile'"
+      >&2 echo "ERROR: profile = '$profile'"
       exit 1
     fi
 }
 
 function set_packages_param {
-    DEPS="libusb-1.0-0 libusb-dev  libusb-1.0-0-dev libreadline-dev libreadline6-dev libcairo2-dev subversion git" # compatible ubuntu 18.04! #liblua5.1-0 lua5.1 liblua5.1-0-dev lua5.2 liblua5.2-dev
+
+    # echo "Instalando en: $OSNAME $RELEASN $CODENM"
+
+    if [ "$RELEASN" == '18.04' ] && [ "$OSNAME" == 'Ubuntu' ]
+     then
+      DEPS="libusb-1.0-0 libusb-dev  libusb-1.0-0-dev libreadline-dev libcairo2-dev subversion git" # libreadline6-dev #liblua5.1-0 lua5.1 liblua5.1-0-dev lua5.2 liblua5.2-dev
+      # apt selecciona libreadline-dev sobre libreadline6-dev, 
+      # si dejamos los dos, entonces tools/check_pkgs informa que faltan dependencias y se llama a apt
+    else
+      #TODO: checkear dependencias en ubuntu 16.04 y debian 7.11
+      DEPS="libusb-1.0-0 libusb-dev  libusb-1.0-0-dev libreadline-dev libreadline6-dev libcairo2-dev subversion git" #liblua5.1-0 lua5.1 liblua5.1-0-dev lua5.2 liblua5.2-dev
+    fi
     # tecgraf deps "lua5.1 liblua5.1-0-dev lua5.2 liblua5.2-dev libfreetype6-dev" # libftgl-dev zlib1g-dev
 
     [[ "$PRINT_SELEC" == "Yes" ]] && {
@@ -64,42 +75,79 @@ function set_packages_param {
 }
 
 function install_chdkptp {
-    echo "Verificando directorio para instalación"
-    ./tools/check_src_dir $CHDKPTP_DIR && echo "OK" || {
-        echo "error: no se pudo crear o modificar '$CHDKPTP_DIR'"
-        exit 1
-    }
+	echo "Verificando directorio para instalación"
+	"$OWN_DIR/tools/check_src_dir" "$CHDKPTP_DIR" && echo "OK" || {
+	    >&2 echo "ERROR: no se pudo crear o modificar '$CHDKPTP_DIR'"
+	    exit 1
+	}
 
-    if ! ./tools/check_pkgs $DEPS; then
-        if [ "root" != "$CURRENT_USER" ]; then
-            echo "para instalar paquetes con apt-get es necesario hacerse root..."
-            # todo check if deb-src enabled
-            ./tools/run_as_root "apt-get install" "$DEPS" || {
-                echo "error al instalar con apt-get"
-                exit 1
-            }
-        else
-            apt-get install $DEPS || {
-                echo "error al instalar con apt-get"
-                exit 1
-            }
-        fi
-    fi
-    check_tecgraf_ver || { echo "ERROR: dependencias insastifechas: librerías tecgraf. Ejecute '/opt/src/instaladores/tecgraf'"; exit 1; }
-    svn co http://subversion.assembla.com/svn/chdkptp/trunk "$CHDKPTP_DIR"
-    cd "$CHDKPTP_DIR"
-    if [ "${CHDKPTP_VER}" != "" ]; then
-      echo "revirtiendo a la versión '${CHDKPTP_VER}'..."
-      svn up -r${CHDKPTP_VER} || exit 1
-    fi
-    config_file=`get_config_file`
-    echo "$config_file" > config.mk
-    make && return 0 || return 1
+	if ! "$OWN_DIR/tools/check_pkgs" $DEPS; then
+	    if [ "root" != "$CURRENT_USER" ]; then
+	        if [ "$ORIG_DPKG_PATH" != "" ]; then
+	    			current_folder="$PWD"
+              	cd "$ORIG_DPKG_PATH"
+  	            "$OWN_DIR/tools/run_as_root" "dpkg -i" *.deb || {
+  	                >&2 echo "ERROR al instalar con dpkg"
+  	                exit 1
+  	            }
+  	            cd "$current_folder"
+	        else
+		        echo "para instalar paquetes con apt-get es necesario hacerse root..."
+		        "$OWN_DIR/tools/run_as_root" "apt-get install" "$DEPS" || {
+		            >&2 echo "ERROR al instalar con apt-get"
+		            exit 1
+		        }
+	        fi
+	    else
+	    	  if [ "$ORIG_DPKG_PATH" != "" ]; then
+               current_folder="$PWD"
+           	   cd "$ORIG_DPKG_PATH"
+               dpkg -i *.deb || {
+                   >&2 echo "ERROR al instalar con dpkg"
+                   exit 1
+               }
+               cd "$current_folder"
+           else
+		        apt-get install $DEPS || {
+		            >&2 echo "ERROR al instalar con apt-get"
+		            exit 1
+		        }
+		     fi
+	    fi
+	fi
+	
+	
+	if [ "$ORIG_URL" != "" ]; then
+	   FILE="${ORIG_URL##*/}"
+	   FILE_WE=`basename $FILE tar.gz`
+		wget -N "$ORIG_URL" -P "$CHDKPTP_DIR" || exit 1
+		cd "$CHDKPTP_DIR" || exit 1
+		tar xzvf "$FILE"
+		cd "$FILE_WE" || { echo "no existe $FILE_WE! falló la instalación"; exit 1; }
+	elif [ "$ORIG_PATH" != "" ]; then
+	   FILE="${ORIG_PATH##*/}"
+	   FILE_WE=`basename $FILE tar.gz`
+		cp -rp "$ORIG_PATH" "$CHDKPTP_DIR"/ || exit 1
+		cd "$CHDKPTP_DIR" || exit 1
+		tar xzvf "$FILE"
+		cd "$FILE_WE" || { echo "no existe $FILE_WE! falló la instalación"; exit 1; }	
+	else
+		svn co http://subversion.assembla.com/svn/chdkptp/trunk "$CHDKPTP_DIR"
+		cd "$CHDKPTP_DIR"
+		if [ "${CHDKPTP_VER}" != "" ]; then
+			echo "revirtiendo a la versión '${CHDKPTP_VER}'..."
+			svn up -r${CHDKPTP_VER} || exit 1
+		fi
+	fi
+	config_file=`get_config_file`
+	echo "$config_file" > config.mk
+	make && return 0 || return 1
 }
 
 function get_config_file {
-  IUP_LIB_DIR=`$TECGRAF_INSTALLER print_path=iup`
-  CD_LIB_DIR=`$TECGRAF_INSTALLER print_path=cd`
+  IUP_LIB_DIR=`$TECGRAF_COMMAND print_path=iup tecdir_path=$TECGRAF_PATH`
+  CD_LIB_DIR=`$TECGRAF_COMMAND print_path=cd tecdir_path=$TECGRAF_PATH`
+  if [[ "$IUP_LIB_DIR" == "" ]] || [[ "$CD_LIB_DIR" == "" ]]; then exit 1; fi
   config_file_d="
 IUP_SUPPORT=1
 CD_SUPPORT=1
@@ -116,7 +164,7 @@ IUP_INCLUDE_DIR=${IUP_LIB_DIR}/include
 CD_LIB_DIR=${CD_LIB_DIR}
 CD_INCLUDE_DIR=${CD_LIB_DIR}/include
 "
-#TODO!! chequera config_file_u!!
+#TODO!! chequear config_file_u!!
   config_file_u="
 IUP_SUPPORT=1
 CD_SUPPORT=1
@@ -152,10 +200,8 @@ function test_chdkptp {
   export LUA_PATH="./lua/?.lua"
   chdkptp_out=$( ./chdkptp -h | head -n 1 )
   if [ "$chdkptp_out" == "CHDK PTP control utility" ]; then
-    echo "chdkptp instalado con éxito"
     return 0
   else
-    echo "chdkptp no instalado"
     return 1
   fi
 }
@@ -163,10 +209,10 @@ function test_chdkptp {
 function check_tecgraf_ver { # tambien version!
   fail=''
   for lib in 'iup' 'cd' 'im'; do
-    if ${TECGRAF_INSTALLER} "print_ver=${lib}" > /dev/null 2>&1
+    if ${TECGRAF_COMMAND} "print_ver=${lib}" > /dev/null 2>&1
      then
       required_ver=$( eval echo "\$${lib^^}_VER" )
-      installed_ver=`${TECGRAF_INSTALLER} "print_ver=${lib}"`
+      installed_ver=`${TECGRAF_COMMAND} "print_ver=${lib}"`
       echo -n "${lib}: instalada:'$installed_ver' requerida:'$required_ver' .."
       [[ "$installed_ver" == "$required_ver" ]] && {
         echo "OK"
@@ -175,7 +221,7 @@ function check_tecgraf_ver { # tambien version!
         fail="Yes"
       }
     else
-      echo "ERROR: '$lib' no instalada."
+      >&2 echo "ERROR: '$lib' no instalada."
       return 1
     fi
   done
@@ -190,27 +236,138 @@ function check_tecgraf_ver { # tambien version!
 }
 #[[ "`uname -m`" == "x86_64" ]] && TYPE="_64" || TYPE=""
 
-OWN_PATH="$PWD/$0"
+OSNAME=`lsb_release -is`
+CODENM=`lsb_release -cs`
+RELEASN=`lsb_release -rs`
+
+if [ "$RELEASN" == '18.04' ] && [ "$OSNAME" == 'Ubuntu' ]; then
+   : 
+else
+	echo "Este instalador no ha sido probado en $OSNAME $RELEASE"
+	echo "OK en Ubuntu 18.04"
+	echo "continuar? (s/N)"
+	read tecla
+	if [ "$tecla" != "s" ] || [ "$tecla" != "S" ]; then exit 0; fi
+fi
+
+OWN_SCRIPT_DIR=$(dirname "$0")
+cd "$OWN_SCRIPT_DIR"
+OWN_DIR="$(pwd -P)"
+OWN_PATH="$OWN_DIR/$0"
+
 CURRENT_USER="$USER"
-TECGRAF_INSTALLER="$PWD/tecgraf" # TODO!!!
+
+TECGRAF_COMMAND="$PWD/tecgraf"
+
 SRCDIR=/opt/src
 CHDKPTP_DIR=$SRCDIR/chdkptp
+TECGRAF_PATH=$SRCDIR/tecgraf
 
-case "$1" in
-    uninstall)
-    ;;
-    '' | install)
-        set_chdkptp_profile "$2" # $2=profile=d\u
-        set_packages_param
-        install_chdkptp || exit 1
-        test_chdkptp && exit 0 || exit 1
-    ;;
-    test)
-        test_chdkptp && exit 0 || exit 1
-    ;;
-    *)
-        echo "ERROR: parametro desconocido '$1'"
-        exit 1
+PROFILE_OPTION=''
+ACTION=''
+
+ORIG_DPKG_PATH=""
+
+if [ "$1" == "" ]; then
+   ACTION="install"
+else
+	while [ $# -ne 0 ]
+	do
+	   arg="$1"
+		case "$arg" in
+		   profile=*)
+		   	PROFILE_OPTION="${arg#*=}"
+		   ;;
+		   tecgraf_path=*)
+		   	ALT_TECGRAF_PATH="${arg#*=}"
+		   ;;
+		   chdkptp_path=*)
+		   	ALT_CHDKPTP_DIR="${arg#*=}"
+		   ;;
+		   orig_path=*)
+		   	ORIG_PATH="${arg#*=}"
+		   ;;
+		   orig_dpkg_path=*)
+		   	ORIG_DPKG_PATH="${arg#*=}"
+		   ;;
+		   orig_url=*)
+		   	ORIG_URL="${arg#*=}"
+		   ;;
+		   uninstall)
+		   	ACTION='uninstall'
+		   ;;
+		   install)
+		   	ACTION='install'
+		   ;;
+		   test)
+		   	ACTION='test'
+		   ;;
+		   *)
+	      	>&2 echo "ERROR: parametro desconocido '$1'"
+		      exit 1
+		esac
+		shift
+	done
+fi
+
+if [ "$ALT_TECGRAF_PATH" != "" ]; then
+	echo "Comprobando '$ALT_TECGRAF_PATH'"
+	[[ -d "$ALT_TECGRAF_PATH" ]] || { echo "'$ALT_TECGRAF_PATH' no existe"; exit 1; }
+	TECGRAF_PATH="$ALT_TECGRAF_PATH"
+fi
+
+if [ "$ALT_CHDKPTP_DIR" != "" ]; then
+	echo "Comprobando '$ALT_CHDKPTP_DIR'"
+	[[ -d "$ALT_CHDKPTP_DIR" ]] || { echo "'$ALT_CHDKPTP_DIR' no existe"; exit 1; }
+	CHDKPTP_DIR="$ALT_CHDKPTP_DIR"
+fi
+
+if [[ "$CHDKPTP_DIR" =~ ^"/opt/src" ]]; then
+	echo "Verificando directorio /opt/src"
+	"$OWN_DIR/tools/check_src_dir" "/opt/src" && echo "OK" || {
+	    >&2 echo "ERROR: no existe o permisos insuficientes en '/opt/src'"
+	    exit 1
+	}
+fi
+
+if [ "$ORIG_PATH" != "" ]; then
+	echo "Comprobando '$ORIG_PATH'"
+	[[ -d "$ORIG_PATH" ]] || { echo "'$ORIG_PATH' no existe"; exit 1; }
+fi
+
+if [ "$ORIG_DPKG_PATH" != "" ]; then
+	echo "Comprobando $ORIG_DPKG_PATH"
+	[[ -d "$ORIG_DPKG_PATH" ]] || { echo "'$ORIG_DPKG_PATH' no existe"; exit 1; }
+fi
+
+
+case "$ACTION" in
+   install)
+      test_chdkptp && { echo "chdkptp ya esta instalado"; exit 0; }
+      set_chdkptp_profile "$PROFILE_OPTION" # $2=profile=d\u
+      check_tecgraf_ver || { echo "Dependencias insastifechas: librerías tecgraf. Ejecute '/opt/src/instaladores/tecgraf'"; exit 1; }
+      set_packages_param
+      install_chdkptp || exit 1
+      test_chdkptp && { 
+      	echo "chdkptp instalado con éxito en '$CHDKPTP_DIR'!"
+      	exit 0
+      } || { 
+      	echo "ERROR: chdkptp no se instaló!"
+      	exit 1 
+      }
+   ;;
+   uninstall)
+      #TODO
+   ;;
+   test)
+      test_chdkptp && { 
+      	echo "chdkptp instalado en '$CHDKPTP_DIR'"
+      	exit 0
+      } || { 
+      	echo "chdkptp NO está instalado en '$CHDKPTP_DIR'"
+      	exit 1 
+      }
+   ;;
 esac
 
 exit 0
diff --git a/chdkptp_avoid_interactions b/chdkptp_avoid_interactions
--- a/chdkptp_avoid_interactions
+++ b/chdkptp_avoid_interactions
@@ -51,11 +51,12 @@ function modify_udev_rules {
         ./tools/run_as_root udevadm control --reload || return 1
         # udevadm hwdb --update && \
         # udevadm control --reload-rules || return 1
-
+        echo "OK"
     else
         cp "$tmp_folder/$libgphoto2_rules" "$etc_rules/$libgphoto2_rules" || return 1
         cp "$tmp_folder/$libgphoto2_hwdb" "$etc_hwdb/$libgphoto2_hwdb" || return 1
         udevadm control --reload || return 1
+        echo "OK"
     fi
   }
 }
@@ -84,4 +85,4 @@ OSNAME=`lsb_release -is`
 CODENM=`lsb_release -cs`
 RELEASN=`lsb_release -rs`
 
-modify_udev_rules || exit 1
+modify_udev_rules || { echo "ocurrio un error!"; exit 1; }
diff --git a/scantailor-advanced b/scantailor-advanced
--- a/scantailor-advanced
+++ b/scantailor-advanced
@@ -5,7 +5,9 @@ if [ "$(id -u)" != "0" ]; then
    exit 1
 fi
 
-SCANTAILOR_SRC_DIR='/opt/src/scantailor-enhanced'
+SCANTAILOR_SRC_DIR='/opt/src/scantailor-advanced'
+REMOTE_SRC='files/bibliohack.org/packages'
+LOCAL_SRC='/opt/bibliohack/packages'
 
 # ---------------------------------------------------------------------------------------------------- #
 
@@ -41,15 +43,19 @@ function check_deb_src() {
   return 0
 }
 
-function check_scantailor_enh() {
-   [[ -x $SCANTAILOR_SRC_DIR/scantailor-cli ]] && {
-	$SCANTAILOR_SRC_DIR/scantailor-cli -h | grep -q "disable-content-detection" && return 0 || return 1
+function check_scantailor_adv() {
+   [[ -x $SCANTAILOR_SRC_DIR/build/scantailor ]] && return 0 || return 1
    } || return 1 ;
 }
 
 # ---------------------------------------------------------------------------------------------------- #
 
-check_scantailor_enh && { echo "Scantailor enhanced ya está instalado"; exit 0; }
+echo "este script todavia no fue testeado!!!"
+exit 0
+
+#
+
+check_scantailor_adv && { echo "Scantailor advanced ya está instalado"; exit 0; }
 
 [[ -d $SCANTAILOR_SRC_DIR ]] && { echo "Existe una instalacion previa inconclusa"; exit 0; }
 
@@ -62,33 +68,46 @@ echo "Instalando en: $OSNAME $RELEASN $CODENM"
 
 check_deb_src /etc/apt/sources.list "$CODENM" || { echo ":("; exit 0; }
 
-echo "Instalando scantailor-enhanced en $OSNAME $RELEASN"
+echo "Instalando scantailor-advanced en $OSNAME $RELEASN"
 
 if [[ "$RELEASN" == '18.04' ]] && [ "$OSNAME" == 'Ubuntu' ]
  then
-   # apt-rdepends -b --follow=DEPENDS scantailor
-   SCANTAILOR_DEV_DEP='cmake build-essential libboost-all-dev libjpeg8-dev libtiff5-dev libpng-dev libqt4-dev zlib1g-dev libxrender-dev txt2man xauth xvfb git subversion' 
-   # apt-cache depends scantailor
-   SCANTAILOR_BIN_DEP='libc6 libgcc1 libjpeg8 libqt4-xml libqtcore4 libqtgui4 libstdc++6 libtiff5 libxrender1' # libpng16-16 ? # libjpeg8-dev libjpeg-dev libtiff5-dev libpng12-dev zlib1g-dev libboost-all-dev 
-elif [[ "$RELEASN" == '16.04' ]] && [ "$OSNAME" == 'Ubuntu' ]
- then
-   # apt-rdepends -b --follow=DEPENDS scantailor
-   SCANTAILOR_DEV_DEP='cmake build-essential libboost-all-dev libjpeg8-dev libtiff5-dev libpng12-dev libqt4-dev zlib1g-dev libxrender-dev txt2man xauth xvfb git subversion' 
-   # apt-cache depends scantailor
-   SCANTAILOR_BIN_DEP='libc6 libgcc1 libjpeg8 libpng12-0 libqt4-xml libqtcore4 libqtgui4 libstdc++6 libtiff5 libxrender1' # libjpeg8-dev libjpeg-dev libtiff5-dev libpng12-dev zlib1g-dev libboost-all-dev 
-elif  [ "$RELEASN" == '7.11' ] && [ "$OSNAME" == 'Debian' ]
- then
-   # apt-rdepends -b --follow=DEPENDS scantailor
-   SCANTAILOR_DEV_DEP='cmake build-essential libboost-dev libboost-test-dev libjpeg-dev libpng-dev libqt4-dev libqt4-opengl-dev libtiff-dev libxrender-dev txt2man xauth xvfb git subversion' # checkinstall
-   # apt-cache depends scantailor
-   SCANTAILOR_BIN_DEP='libc6 libgcc1 libjpeg8 libpng12-0 libqt4-xml libqtcore4 libqtgui4 libstdc++6 libtiff5 libxrender1' # libjpeg8-dev libjpeg-dev libtiff5-dev libpng12-dev zlib1g-dev libboost-all-dev 
+   echo ""
+   echo "Descargando cmake 3.12.."
+   cd /opt/src && wget https://cmake.org/files/v3.12/cmake-3.12.4.tar.gz && tar xzvf cmake-3.12.4.tar.gz && cd cmake-3.12.4 || exit 1
+   echo "cmake 3.12 descargado OK"
+   echo "Compilando cmake 3.12 e instalando.."
+   ./bootstrap && make -j4
+   echo "cmake 3.12 compilado OK"
+   echo "Desinstalando version previa de cmake..."
+   sudo apt-get -y remove cmake && sudo apt-get -y purge --auto-remove cmake || exit 1
+   echo "Version previa de cmake desinstalada"
+   echo "instalando cmake 3.12"
+   sudo make install
 
+   # apt-rdepends -b --follow=DEPENDS scantailor
+
+   #SCANTAILOR_REMOVE_DEP='libjpeg-dev libjpeg8-dev libjpeg-turbo8-dev'
+   # debido a este bug en ubuntu 18.04 entran en conflicto (da error el prceso de instalcion con libjpeg9-dev)
+   # sin emvbargo compilo ok con libjpeg8
+   
+   # a artir de la sugerencias para ubuntu de scantailor-advanced
+   SCANTAILOR_DEV_DEP='libboost-all-dev build-essential gcc-7 g++-7 libjpeg-dev libpng-dev libtiff5-dev libboost-test1.65-dev libboost-test1.65.1 qtbase5-dev qttools5-dev qttools5-dev-tools libqt5opengl5-dev libpthread-stubs0-dev'
+   
+   # SCANTAILOR_DEV_DEP=' libtiff5-dev libpng-dev libqt4-dev zlib1g-dev libxrender-dev txt2man xauth xvfb git subversion' 
+   # apt-cache depends scantailor
+   
+   ## esto falta revisar!! probablemente estos paquetes se instalen como dependencias de SCANTAILOR_DEV_DEP
+   SCANTAILOR_BIN_DEP='libc6 libgcc1 libjpeg8 libqt4-xml libqtcore4 libqtgui4 libstdc++6 libtiff5 libxrender1' # libpng16-16 ? # libjpeg8-dev libjpeg-dev libtiff5-dev libpng12-dev zlib1g-dev libboost-all-dev    
 else
   echo "Su sistema operativo '$OSNAME' '$CODENM' '$RELEASN', no esta soportado"
   exit 0
 fi
 
 apt-get update
+
+# echo "Desinstalando dependencias que entran en conflicto"
+# apt-get remove -y $SCANTAILOR_REM_DEP && echo "OK" || { echo "FAIL"; exit 1; }
 
 echo "Instalando dependencias de Scantailor (binario)"
 apt-get install -y $SCANTAILOR_BIN_DEP && echo "OK" || { echo "FAIL"; exit 1; }
@@ -102,28 +121,29 @@ echo "Comprobando directorio para compilación"
 cd /opt/src
 
 echo "Clonando repositorio Scantailor en $SCANTAILOR_SRC_DIR"
-if [[ "$RELEASN" =~ '16.04'|'18.04' ]] && [ "$OSNAME" == 'Ubuntu' ]
+if [[ "$RELEASN" == '18.04' ]] && [ "$OSNAME" == 'Ubuntu' ]
  then
-   git clone -b enhanced https://github.com/d-a-l/scantailor.git $SCANTAILOR_SRC_DIR
-elif  [ "$RELEASN" == '7.11' ] && [ "$OSNAME" == 'Debian' ]
- then
-   git clone -b enhanced https://github.com/scantailor/scantailor.git $SCANTAILOR_SRC_DIR
+   git clone https://github.com/4lex4/scantailor-advanced.git $SCANTAILOR_SRC_DIR
+else
+  echo "Su sistema operativo '$OSNAME' '$CODENM' '$RELEASN', no esta soportado"
+  exit 0   
 fi
 
 if [[ -d "$SCANTAILOR_SRC_DIR" ]]
  then
    cd $SCANTAILOR_SRC_DIR
-   echo "Compilando Scantailor enhanced"
-   cmake . && make
+   echo "Compilando Scantailor advanced"
+   mkdir build && cd build || { echo "FAIL"; exit 1; }
+   cmake -G "Unix Makefiles" --build ..  || { echo "FAIL"; exit 1; }
+   make -j `nproc` || { echo "FAIL"; exit 1; }
    # checkinstall --pkgname scantailor --pkgversion ?? --pkgrelease ??
 else
    echo "no existe '$SCANTAILOR_SRC_DIR'"
 fi
 
-check_scantailor_enh && echo "Scantailor instalado exitosamente en '$SCANTAILOR_SRC_DIR'" || { echo "Falló la instalacion de Scantailor enhanced"; exit 1; } 
+check_scantailor_enh && echo "Scantailor Advanced instalado exitosamente en '$SCANTAILOR_SRC_DIR'" || { echo "Falló la instalacion de Scantailor enhanced"; exit 1; } 
 
-echo "Para ejecutar scantailor-enhanced use:"
-echo " '$SCANTAILOR_SRC_DIR/scantailor-cli' (linea de comandos) ó"
+echo "Para ejecutar scantailor-advanced use:"
 echo " '$SCANTAILOR_SRC_DIR/scantailor' (interfase gráfica)"
 
 exit 0
diff --git a/tecgraf b/tecgraf
--- a/tecgraf
+++ b/tecgraf
@@ -12,10 +12,17 @@ Uso:
                                    -> Imprime versión iup|cd|im instalada para
                                       la version de lua indicada (51 por defecto)
 
-    tecgraf print_path=iup|cd|im   -> Imprime la ruta a iup|cd|im para chdkptp.
+    tecgraf print_path=iup|cd|im [tecdir_path=<path>]
+                                   -> Imprime la ruta a iup|cd|im para chdkptp.
 
-    tecgraf install profile=d|u    -> instala iup,cd,im profile de forma
+    tecgraf install [profile=d|u] [tecdir_path=<path>] 
+                    [orig_url=<url>|orig_path=<path>] [orig_dpkg_path=<path>]
+                                   -> instala iup,cd,im profile de forma
                                       no interactiva
+                                      orig_url -> url alternativa con binarios tecgraf
+                                      orig_path -> ruta local a carpeta con binarios tecgraf
+                                      orig_dpkg_path -> ruta local a paquetes para dpkg
+    
 "
 # chequeado en Ubuntu 16.04 OK perfil 'd', no instala LUA 5.2
 
@@ -26,11 +33,17 @@ Uso:
 # TODO: debian probar si funciona o no run_as_root
 # TODO: ubuntu 16.04 profile=u OK
 
+function echoo() {
+	if [ "$QUIET" == "" ]; then
+		echo "$1"
+   fi
+}
+
 function set_tecgraf_profile {
 
-    if [[ "$1" =~ ^profile=[d|u]*$ ]]
+    if [[ "$1" =~ "d"|"u" ]]
      then
-       profile="${1#*=}"
+       profile="$1"
        echo "perfil de intalacion: '$profile'"
     else
       echo "Seleccione el perfil de instalación para Tecgraf:"
@@ -48,7 +61,7 @@ function set_tecgraf_profile {
 
       echo "Seleccione fuente de descarga:"
       echo " - 's' descargar desde sourceforge"
-      echo " - 'a' alternativo"
+      echo " - 'a' bibliohack.org"
       #echo " por defecto usar tarballs/sourceforgue/alternativo" TODO
       echo "(por defecto 's')"
       read -p ">> " sel
@@ -86,7 +99,7 @@ function set_tecgraf_profile {
       IMLUA_EXTRA_TAR=""      #'true'
       lua_vers=( '51' )
     else
-      echo "ERROR: profile = '$profile'"
+      >&2 echo "ERROR: profile = '$profile'"
       exit 1
     fi
 }
@@ -166,12 +179,12 @@ function install_libs {
         echo -n "para instalar iup, cd y im en el sistema es "
         echo "necesario hacerse root..."
         for item in "${items[@]}"; do echo "$item"; done
-        ./tools/run_as_root ./tools/tecgraf/install_libs "${items[@]}" || {
+        "$OWN_DIR/tools/run_as_root" "$OWN_DIR/tools/tecgraf/install_libs" "${items[@]}" || {
             echo "install_libs (root) falló"
             return 1
         }
     else
-       ./tools/tecgraf/install_libs "${items[@]}"  || {
+       "$OWN_DIR/tools/tecgraf/install_libs" "${items[@]}"  || {
            echo "install_libs falló"
            return 1
        }
@@ -264,7 +277,7 @@ function get_installed_libs {
 
 function list_available_folders {
   current_folder="$PWD"
-  cd $TECDIR
+  cd "$TECDIR"
   echo "Instalaciones tecgraf disponibles en '$TECDIR'"
   echo ""
   ls -1d */
@@ -319,12 +332,12 @@ function uninstall_tecgraf {
         echo ""
         echo -n "para desinstalar iup, cd y im en el sistema es "
         echo "necesario hacerse root..."
-        ./tools/run_as_root ./tools/tecgraf/install_libs "${items[@]}" || {
+        "$OWN_DIR/tools/run_as_root" "$OWN_DIR/tools/tecgraf/install_libs" "${items[@]}" || {
             echo "install_libs (root) falló"
             return 1
         }
     else
-       ./tools/tecgraf/install_libs "${items[@]}"  || {
+       "$OWN_DIR/tools/tecgraf/install_libs" "${items[@]}"  || {
            echo "install_libs falló"
            return 1
        }
@@ -336,24 +349,44 @@ function uninstall_tecgraf {
 
 function install_tecgraf {
     echo "Verificando directorio para instalación"
-    ./tools/check_src_dir $TECDIR && echo "OK" || {
-        echo "error: no se pudo crear o modificar '$TECDIR'"
+    "$OWN_DIR/tools/check_src_dir" "$TECDIR" && echo "OK" || {
+        >&2 echo "ERROR: no se pudo crear o modificar '$TECDIR'"
         exit 1
     }
 
-    if ! ./tools/check_pkgs $DEPS; then
+    if ! "$OWN_DIR/tools/check_pkgs" $DEPS; then
         if [ "root" != "$CURRENT_USER" ]; then
             echo "para instalar paquetes con apt-get es necesario hacerse root..."
             # todo check if deb-src enabled
-            ./tools/run_as_root "apt-get install" "$DEPS" || {
-                echo "error al instalar con apt-get"
-                exit 1
-            }
+            if [ "$ORIG_DPKG_PATH" != "" ]; then
+               current_folder="$PWD"
+            	cd "$ORIG_DPKG_PATH"
+	            "$OWN_DIR/tools/run_as_root" "dpkg -i" *.deb || {
+	                >&2 echo "ERROR al instalar con dpkg"
+	                exit 1
+	            }
+	            cd "$current_folder"
+            else
+	            "$OWN_DIR/tools/run_as_root" "apt-get install" "$DEPS" || {
+	                >&2 echo "ERROR al instalar con apt-get"
+	                exit 1
+	            }
+            fi
         else
-            apt-get install $DEPS || {
-                echo "error al instalar con apt-get"
-                exit 1
-            }
+            if [ "$ORIG_DPKG_PATH" != "" ]; then
+                current_folder="$PWD"
+            	cd "$ORIG_DPKG_PATH"
+	            dpkg -i *.deb || {
+	                >&2 echo "ERROR al instalar con dpkg"
+	                exit 1
+	            }
+	            cd "$current_folder"
+            else
+	            apt-get install $DEPS || {
+	                >&2 echo "ERROR al instalar con apt-get"
+	                exit 1
+	            }
+	        fi
         fi
     fi
 
@@ -362,15 +395,20 @@ function install_tecgraf {
                $IM_TAR  $IMLUA51_TAR  $IMLUA52_TAR
     do
         dest=`basename $tar .$TAR_EXT`
-        echo -e "\ndescargando '$tar' para instalar en '$dest'\n"
-        if [ "$SOURCEFORGE" == "Yes" ]
-         then
-          URL="$( sourceforge_link $tar )"
+        if [ "$ORIG_PATH" != "" ]; then
+           echo -e "\ncopiando '$tar' desde '$ORIG_PATH' para instalar en '$dest'\n"
+          "$OWN_DIR/tools/tecgraf/copy_and_untar" $tar "$ORIG_PATH" "$TECDIR" "$dest" || exit 1
         else
-          URL="$ALT_URL"
+           echo -e "\ndescargando '$tar' para instalar en '$dest'\n"
+           if [ "$SOURCEFORGE" == "Yes" ]
+            then
+             URL="$( sourceforge_link $tar )"
+           else
+             URL="$ALT_URL"
+           fi
+           if [[ ! "$URL" ]]; then >&2 echo "ERROR: falló URL = '$URL'"; exit 1; fi
+           "$OWN_DIR/tools/tecgraf/download_and_untar" $tar $URL "$TECDIR" "$dest" || exit 1
         fi
-        if [[ ! "$URL" ]]; then echo " ERROR: falló URL = '$URL'"; exit 1; fi
-        ./tools/download_and_untar $tar $URL $TECDIR $dest || exit 1
     done
 
     install_libs || exit 1
@@ -400,7 +438,7 @@ function test_tecgraf {
             fi
          done
       else
-         echo "ERROR: debug: '$lua_bin' no existe"
+         >&2 echo "ERROR: debug: '$lua_bin' no existe"
          fail="Yes"
       fi
     done
@@ -411,7 +449,7 @@ function print_version {
   [[ "$1" =~ ^(iup|im|cd)$ ]] && {
     lib="$1"
   } || {
-    echo "ERROR: debug: print_version: valor no admitido: '$1'"
+    >&2 echo "ERROR: debug: print_version: valor no admitido: '$1'"
     return 1
   }
 
@@ -423,12 +461,12 @@ function print_version {
       lua_ver="$2"
       lua_bin="/usr/bin/lua${lua_ver:0:1}.${lua_ver:1:1}"
     } || {
-      echo "ERROR: debug: Versión lua no válida: '$2'"
+      >&2 echo "ERROR: debug: Versión lua no válida: '$2'"
       return 1
     }
   }
 
-  [[ -f "$lua_bin" ]] || { echo "ERROR: '$lua_bin' no instalado."; return 1; } #TODO chequear lua path para debian!!
+  [[ -f "$lua_bin" ]] || { >&2 echo "ERROR: '$lua_bin' no instalado."; return 1; } #TODO chequear lua path para debian!!
   $lua_bin -e "require '${lib}lua'" &> /dev/null && {
     $lua_bin -e "require '${lib}lua'; print(${lib}.Version())"
     return 0
@@ -439,7 +477,8 @@ function print_version {
 }
 
 function print_path {
-  [[ "$1" =~ ^(iup|im|cd)$ ]] && lib="$1" || { echo "ERROR: debug: print_path: valor no admitido: '$1'"; return 1; }
+  [[ "$1" =~ ^(iup|im|cd)$ ]] && lib="$1" || { >&2 echo "ERROR: debug: print_path: valor no admitido: '$1'"; return 1; }
+  [[ -d "${TECDIR}" ]] || { >&2 echo "ERROR! no existe '$TECDIR'"; return 1; }
 
   VER=`print_version "${lib}"`
   lib_path="${TECDIR}/${lib}-${VER}_${KERNEL}${TYPE}_lib"
@@ -447,7 +486,7 @@ function print_path {
     echo "${lib_path}"
     return 0
   } || {
-    echo "ERROR! no existe '${lib_path}' para la versión ${VER} de '${lib}'."
+    >&2 echo "ERROR! no existe '${lib_path}' para la versión ${VER} de '${lib}'."
     return 1
   }
 }
@@ -464,63 +503,138 @@ TAR_EXT="tar.gz"
 [[ "`uname -m`" == "x86_64" ]] && TYPE="_64" || TYPE=""
 
 ALT_URL='http://codex.bibliohack.org/media/files/tecgraf'
-SOURCEFORGE="Yes"
-OWN_PATH="$PWD/$0"
+SOURCEFORGE="No"
+
+OWN_SCRIPT_DIR=$(dirname "$0")
+cd "$OWN_SCRIPT_DIR"
+OWN_DIR="$(pwd -P)"
+OWN_PATH="$OWN_DIR/$0"
+
 CURRENT_USER="$USER"
+
+QUIET=""
 
 SRCDIR=/opt/src
 TECDIR=$SRCDIR/tecgraf
+PROFILE_OPT=''
+ACTION=''
+ORIG_PATH=''
 
-arg="$1"
+if [ "$1" == "" ]; then
+   ACTION="install"
+else
+   while [ $# -ne 0 ]
+   do
+      arg="$1"
+      case "$arg" in
+          tecdir_path=*)
+              TECDIR_ALT="${arg#*=}"
+          ;;
+          profile=*)
+              PROFILE_OPT="${arg#*=}"
+          ;;
+          orig_url=*)
+              ALT_URL="${arg#*=}"
+          ;;
+          orig_path=*)
+              ORIG_PATH="${arg#*=}"
+          ;;
+          orig_dpkg_path=*)
+              ORIG_DPKG_PATH="${arg#*=}"
+          ;;
+          uninstall)
+              ACTION="uninstall"
+          ;;
+          install)
+              ACTION="install"
+          ;;
+          print_ver=*)
+              ACTION=""
+              QUIET="quiet"
+              parg="${arg#*=}"
+              parg1="${parg%,*}"
+              parg2="${parg#*,}"
+              [[ "$parg1" == "$parg2" ]] &&{
+                print_version "$parg1" || exit 1
+              } || {
+                print_version "$parg1" "$parg2" || exit 1
+              }
+              exit 0
+          ;;
+          print_path=*)
+              PRINT_PATH_ARG="${arg#*=}"
+              ACTION='print_path'
+              QUIET="quiet"
+          ;;
+          help)
+              echo "$help"
+              exit 0
+          ;;
+          *)
+              >&2 echo "ERROR: parametro desconocido '$1'"
+              echo "$help"
+              exit 1
+          ;;
+      esac
+      shift
+   done
+fi
 
-case "$arg" in
-    uninstall)
-        get_installed_libs || exit 1
-        echo -e "Presione \n ENTER para desinstalar\n 'M' para modificar\n Control+C para salir\n"
-        read -p ">> " continuar
-        if [[ "$continuar" =~ ^(M|m)$ ]]; then
-           list_available_folders
-           modify_libs || exit 1
-        fi
-        set_packages_param
-        uninstall_tecgraf || exit 1
-        test_tecgraf
-    ;;
-    '' | install)
-        get_installed_libs || exit 1
-        if [ "$IUP_VER" ] || [ "$CD_VER" ] || [ "$IM_VER" ]
-         then
-           echo "Existen librerías Tecgraf instaladas en su sistema,"
-           echo "use './tecgraf uninstall' para desinstalarlas."
-           echo
-           exit 1;
-        fi
-        set_tecgraf_profile "$2"
-        set_packages_param
-        install_tecgraf
-        test_tecgraf || exit 1
-    ;;
-    print_ver=*)
-        parg="${arg#*=}"
-        parg1="${parg%,*}"
-        parg2="${parg#*,}"
-        [[ "$parg1" == "$parg2" ]] &&{
-          print_version "$parg1" || exit 1
-        } || {
-          print_version "$parg1" "$parg2" || exit 1
-        }
-    ;;
-    print_path=*)
-        print_path "${arg#*=}" || exit 1
-    ;;
-    help)
-        echo "$help"
-    ;;
-    *)
-        echo "ERROR: parametro desconocido '$1'"
-        echo "$help"
-        exit 1
-    ;;
+if [ "$TECDIR_ALT" != "" ]; then
+	echoo "Comprobando '$TECDIR_ALT'"
+	[[ -d "$TECDIR_ALT" ]] || { echoo "'$TECDIR_ALT' no existe"; exit 1; }
+	[[ -w "$TECDIR_ALT" ]] || { echoo "'$TECDIR_ALT' permisos insuficientes"; exit 1; }
+	TECDIR="$TECDIR_ALT"
+else
+   if [ "$QUIET" == "" ]; then #check_src_dir is not quiet script
+		echo "Verificando directorio /opt/src"
+		"$OWN_DIR/tools/check_src_dir" "/opt/src" && echo "OK" || {
+		    >&2 echo "ERROR: no se pudo crear o modificar '/opt/src'"
+		    exit 1
+		}
+	fi
+fi
+
+if [ "$ORIG_PATH" != "" ]; then
+	echoo "Comprobando '$ORIG_PATH'"
+	[[ -d "$ORIG_PATH" ]] || { echoo "'$ORIG_PATH' no existe"; exit 1; }
+fi
+
+if [ "$ORIG_DPKG_PATH" != "" ]; then
+	echoo "Comprobando $ORIG_DPKG_PATH"
+	[[ -d "$ORIG_DPKG_PATH" ]] || { echoo "'$ORIG_DPKG_PATH' no existe"; exit 1; }
+fi
+
+case "$ACTION" in
+   install)
+      get_installed_libs || exit 1
+      if [ "$IUP_VER" ] || [ "$CD_VER" ] || [ "$IM_VER" ]
+      then
+        echo "Existen librerías Tecgraf instaladas en su sistema,"
+        echo "use './tecgraf uninstall' para desinstalarlas."
+        echo
+        exit 1;
+      fi
+      set_tecgraf_profile "$PROFILE_OPT"
+      set_packages_param
+      install_tecgraf
+      test_tecgraf || exit 1
+   ;;
+   uninstall)
+      get_installed_libs || exit 1
+      echo -e "Presione \n ENTER para desinstalar\n 'M' para modificar\n Control+C para salir\n"
+      read -p ">> " continuar
+      if [[ "$continuar" =~ ^(M|m)$ ]]; then
+         list_available_folders
+         modify_libs || exit 1
+      fi
+      set_packages_param
+      uninstall_tecgraf || exit 1
+      test_tecgraf
+   ;;
+   print_path)
+      print_path "$PRINT_PATH_ARG" || exit 1
+   ;;
 esac
 
 exit 0
diff --git a/tools/check_src_dir b/tools/check_src_dir
--- a/tools/check_src_dir
+++ b/tools/check_src_dir
@@ -3,7 +3,12 @@
 # verifica que la carpeta exista y se pueda escribir
 # si no puede y no es root, pide permisos y lo intenta como root
 
-OWN_PATH="$PWD/$0"
+OWN_SCRIPT_DIR=$(dirname "$0")
+cd "$OWN_SCRIPT_DIR"
+OWN_DIR="$(pwd -P)"
+OWN_PATH="$OWN_DIR/$0"
+
+
 CURRENT_USER="$USER"
 
 [[ "$1" == "" ]] && SRCDIR=/opt/src || SRCDIR="$1"
@@ -11,9 +16,11 @@ CURRENT_USER="$USER"
 if [ "root" == "$CURRENT_USER" ]; then
    [[ -d "$SRCDIR" ]] || { 
       mkdir "$SRCDIR" || {
-         [[ -d "$(dirname "$SRCDIR")" ]] && \
-            echo "error: no se pudo crear '$SRCDIR' porque no existe " ||\
-            echo "verifique que la carpeta padre exista"
+         if [[ -d "$(dirname "$SRCDIR")" ]]; then
+            >&2 echo "error: no se pudo crear '$SRCDIR'"
+         else
+            >&2 echo "verifique que la carpeta padre exista"
+         fi
          exit 1
       }   
    }
@@ -24,7 +31,7 @@ else
          echo ""
          echo "para crear '$SRCDIR' es necesario hacerse root..."
          echo "(use control+c para cancelar)"
-         su root -c "$OWN_PATH $SRCDIR" || { echo "$OWN_PATH falló"; exit 1;}
+         "$OWN_DIR/run_as_root" "mkdir" "$SRCDIR" || { >&2 echo "No pudo crearse '$SRCDIR'"; exit 1;}
       }
    }
    if touch "$SRCDIR/writable_test" 2>/dev/null; then
@@ -34,12 +41,9 @@ else
       echo ""
       echo "para cambiar los permisos en '$SRCDIR' es necesario hacerse root..."
       echo "(use control+c para cancelar)"
-      su root -c "$OWN_PATH $SRCDIR" || { echo "$OWN_PATH falló"; exit 1;}
-      if touch "$SRCDIR/writable_test" 2>/dev/null; then
-         rm "$SRCDIR/writable_test"
-         exit 0
-      else
-         echo "error: root no pudo modificar '$SRCDIR'"
-      fi
+      "$OWN_DIR/run_as_root" "chmod" "a+rw" "$SRCDIR" || { 
+      	>&2 echo "Error: no se pudieron modificar los permisos en '$SRCDIR'"
+      	exit 1
+      }
    fi
 fi
