lot of fixs and improve tecgraf installer

diff --git a/tecgraf b/tecgraf
--- a/tecgraf
+++ b/tecgraf
@@ -1,69 +1,114 @@
 #!/bin/bash
 
-# chequeado en Ubuntu 16.04 OK - volver a chequear con las modificaciones!
-# chequeado en Debian Wheezy 3.8/5.6.1/3.8.2 - no se instala para LUA 5.2, porque para esas versiones no corre la variable USE_LUA51
-# TODO: debian no funciona run_as_root -> probablmente no este pasando los parametros que van en $COMMAND en:  su root -c $COMMAND
+# USO: 
+#    ./tecgraf           -> instala iup/cd/im
+#    ./tecgraf uninstall -> desinstala iup/cd/im
+#    ./tecgraf luatest   -> test si funciona iup/cd/im en lua
+#    nota: el script siempre pregunta por un perfil de instalacion
 
-[[ "$1" == "uninstall" ]] && { UNINSTALL=Yes; shift; }
+# las opciones 'install_libs' o 'uninstall_libs' las ejecuta el propio script cuando
+# necesita volver a ejecutarse como root
 
-IUP_VER="3.8"        #"3.19.1"  #"3.23"
-IUPLUA_EXTRA_TAR=""  #'true'	
-CD_VER="5.6.1"       #"5.10"    #"5.11.1"
-CDLUA_EXTRA_TAR=""	 #'true'
-IM_VER="3.8.2"       #"3.11"    #"3.12"
-IMLUA_EXTRA_TAR=""   #'true'
-NOT_INSTALL_LUA52="Yes"
+# chequeado en Ubuntu 16.04 OK perfil 'd', no instala LUA 5.2
 
-KERNEL="Linux32"            #"Linux44"
-TAR_EXT="tar.gz"
-TYPE=""       #""        #"_64"
-URL='http://codex.bibliohack.org/media/files/tecgraf'
+# TODO: test de errores con
+# ./tecgraf install_tecgraf profile=d || echo "fail"
 
-OWN_PATH="$PWD/$0"
-CURRENT_USER="$USER"
+# volver a chequear en Debian Wheezy 3.8/5.6.1/3.8.2 - no se instala para LUA 5.2, porque para esas versiones no corre la variable USE_LUA51
+# TODO: debian no funciona run_as_root -> probablmente no este pasando los parametros que van en $COMMAND en:  su root -c $COMMAND (ojo, esto esta fixed o no?)
 
-SRCDIR=/opt/src
-TECDIR=$SRCDIR/tecgraf
+function set_tecgraf_profile {
 
-DEPS="lua5.1 liblua5.1-0-dev lua5.2 liblua5.2-dev libfreetype6-dev" # libftgl-dev zlib1g-dev
+    if [[ "$1" =~ ^profile=[d|u]*$ ]] 
+     then
+       profile="${1#*=}"
+       echo "perfil de intalacion: '$profile'"
+    else
+      echo "Seleccione el perfil de instalación para Tecgraf:"
+      echo " - 'd' para versión dalclick"
+      echo " - 'u' para última versión"
+      echo " - 's' para salir"
+      echo "(por defecto 'd')" 
+      read -p ">> " sel
 
-IUP_TAR=iup-${IUP_VER}_${KERNEL}${TYPE}_lib.${TAR_EXT}
-if [ "$IUPLUA_EXTRA_TAR" == "true" ]
- then
-   IUPLUA51_TAR=iup-${IUP_VER}-Lua51_${KERNEL}${TYPE}_lib.${TAR_EXT}
-   IPULUA52_TAR=iup-${IUP_VER}-Lua52_${KERNEL}${TYPE}_lib.${TAR_EXT}
-else
-   IUPLUA_FOLDER=`basename $IUP_TAR .$TAR_EXT`
-fi
+      if [ "$sel" == "u" ]; then profile="u"
+      elif [ "$sel" == "s" ]; then echo "Eligió salir."; exit 0 
+      else profile="d"
+      fi
+      PRINT_SELEC="Yes"
+    fi
 
-CD_TAR=cd-${CD_VER}_${KERNEL}${TYPE}_lib.${TAR_EXT}
-if [ "$CDLUA_EXTRA_TAR" == "true" ]
- then
-   CDLUA51_TAR=cd-${CD_VER}-Lua51_${KERNEL}${TYPE}_lib.${TAR_EXT}
-   CDLUA52_TAR=cd-${CD_VER}-Lua52_${KERNEL}${TYPE}_lib.${TAR_EXT}
- else
-   CDLUA_FOLDER=`basename $CD_TAR .$TAR_EXT`
-fi
+    if [ "$profile" == "u" ]
+     then
+      [[ "$PRINT_SELEC" == "Yes" ]] && echo "Configurando versiones de los paquetes tecgraf para 'última versión' (u)"
+      IUP_VER="3.23"
+      IUPLUA_EXTRA_TAR='true'	
+      CD_VER="5.11.1"
+      CDLUA_EXTRA_TAR='true'
+      IM_VER="3.12"
+      IMLUA_EXTRA_TAR='true'
+      # NOT_INSTALL_LUA52="Yes"
+    elif [ "$profile" == "d" ]
+     then
+      [[ "$PRINT_SELEC" == "Yes" ]] && echo "Configurando versiones de los paquetes tecgraf para 'dalclick' (d)"
+      IUP_VER="3.8"           #"3.19.1"
+      IUPLUA_EXTRA_TAR=""     #'true'	
+      CD_VER="5.6.1"          #"5.10"
+      CDLUA_EXTRA_TAR=""      #'true'
+      IM_VER="3.8.2"          #"3.11"
+      IMLUA_EXTRA_TAR=""      #'true'
+      NOT_INSTALL_LUA52="Yes"
+    else
+      echo "ERROR: profile = '$profile'"
+      exit 1
+    fi
+}
 
-IM_TAR=im-${IM_VER}_${KERNEL}${TYPE}_lib.${TAR_EXT}
-if [ "$IMLUA_EXTRA_TAR" == 'true' ]
- then
-   IMLUA51_TAR=im-${IM_VER}-Lua51_${KERNEL}${TYPE}_lib.${TAR_EXT}
-   IMLUA52_TAR=im-${IM_VER}-Lua52_${KERNEL}${TYPE}_lib.${TAR_EXT}
- else
-   IMLUA_FOLDER=`basename $IM_TAR .$TAR_EXT`
-fi
+function set_packages_param {
 
-echo $IUP_TAR
-echo $IUPLUA51_TAR
-echo $IPULUA52_TAR
-echo $CD_TAR
-echo $CDLUA51_TAR
-echo $CDLUA52_TAR
-echo $IM_TAR
-echo $IMLUA51_TAR
-echo $IMLUA52_TAR
-#exit 1
+    DEPS="lua5.1 liblua5.1-0-dev lua5.2 liblua5.2-dev libfreetype6-dev" # libftgl-dev zlib1g-dev
+
+    IUP_TAR=iup-${IUP_VER}_${KERNEL}${TYPE}_lib.${TAR_EXT}
+    if [ "$IUPLUA_EXTRA_TAR" == "true" ]
+     then
+       IUPLUA51_TAR=iup-${IUP_VER}-Lua51_${KERNEL}${TYPE}_lib.${TAR_EXT}
+       IPULUA52_TAR=iup-${IUP_VER}-Lua52_${KERNEL}${TYPE}_lib.${TAR_EXT}
+    else
+       IUPLUA_FOLDER=`basename $IUP_TAR .$TAR_EXT`
+    fi
+
+    CD_TAR=cd-${CD_VER}_${KERNEL}${TYPE}_lib.${TAR_EXT}
+    if [ "$CDLUA_EXTRA_TAR" == "true" ]
+     then
+       CDLUA51_TAR=cd-${CD_VER}-Lua51_${KERNEL}${TYPE}_lib.${TAR_EXT}
+       CDLUA52_TAR=cd-${CD_VER}-Lua52_${KERNEL}${TYPE}_lib.${TAR_EXT}
+     else
+       CDLUA_FOLDER=`basename $CD_TAR .$TAR_EXT`
+    fi
+
+    IM_TAR=im-${IM_VER}_${KERNEL}${TYPE}_lib.${TAR_EXT}
+    if [ "$IMLUA_EXTRA_TAR" == 'true' ]
+     then
+       IMLUA51_TAR=im-${IM_VER}-Lua51_${KERNEL}${TYPE}_lib.${TAR_EXT}
+       IMLUA52_TAR=im-${IM_VER}-Lua52_${KERNEL}${TYPE}_lib.${TAR_EXT}
+     else
+       IMLUA_FOLDER=`basename $IM_TAR .$TAR_EXT`
+    fi
+
+    [[ "$PRINT_SELEC" == "Yes" ]] && {
+        echo "iup: '$IUP_TAR'"
+        echo "iuplua51: '$IUPLUA51_TAR'"
+        echo "iuplua52: '$IPULUA52_TAR'"
+        echo "cd: '$CD_TAR'"
+        echo "cdlua51: '$CDLUA51_TAR'"
+        echo "cdlua52: '$CDLUA52_TAR'"
+        echo "im: '$IM_TAR'"
+        echo "imlua51: '$IMLUA51_TAR'"
+        echo "imlua52: '$IMLUA52_TAR'"
+        sleep 2
+    }
+}
+
 function run_bash {
     echo ""
     echo "ejecutando '$1' en '$PWD'..."
@@ -207,7 +252,7 @@ function install_tecgraf {
         echo ""
         echo -n "para instalar iup, cd y im en el sistema es "
         echo "necesario hacerse root..."
-        ./tools/run_as_root "$OWN_PATH" "install_libs" || { 
+        ./tools/run_as_root "$OWN_PATH" "install_libs profile=$profile" || { 
             echo "install_libs falló"
             exit 1
         }
@@ -222,7 +267,7 @@ function uninstall_tecgraf {
         echo ""
         echo -n "para desinstalar iup, cd y im en el sistema es "
         echo "necesario hacerse root..."
-        ./tools/run_as_root "$OWN_PATH" "uninstall_libs" || { 
+        ./tools/run_as_root "$OWN_PATH" "uninstall_libs profile=$profile" || { 
             echo "uninstall_libs falló"
             exit 1
         }
@@ -234,43 +279,65 @@ function uninstall_tecgraf {
 function test_tecgraf {
     echo ""
     echo "Verificando instalacion..."
+    fail_test=""
     for lib in 'iup' 'cd' 'im'; do
         lua5.1 -e "require '${lib}lua'" 2>/dev/null \
           && echo "lua5.1: ${lib}lua instalado OK!" \
-          || echo "lua5.1: ${lib}lua NO instalado"
+          || { echo "lua5.1: ${lib}lua NO instalado"; fail_test="Yes"; }
         if [ "$NOT_INSTALL_LUA52" != "Yes" ]
           then
             lua5.2 -e "require '${lib}lua'" 2>/dev/null \
               && echo "lua5.2: ${lib}lua instalado OK!" \
-              || echo "lua5.2: ${lib}lua NO instalado"
+              || { echo "lua5.2: ${lib}lua NO instalado"; fail_test="Yes"; }
         fi
     done
 }
 
 # = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = #
-echo "parametros ---> $1"
-if [ "$1" == "" ]
- then
-    if [ "$UNINSTALL" == "" ]; then
-        install_tecgraf
-    else
+
+[[ "`uname -o`" == "GNU/Linux" ]] || {
+   echo "Este script solo puede utilizarse en sistemas 'GNU/Linux'"
+   exit 1
+}
+KERNEL="Linux32"            #"Linux44" #es para nombre interno del paquete tecgraf
+TAR_EXT="tar.gz"
+[[ "`uname -m`" == "x86_64" ]] && TYPE="_64" || TYPE=""
+
+URL='http://codex.bibliohack.org/media/files/tecgraf'
+
+OWN_PATH="$PWD/$0"
+CURRENT_USER="$USER"
+
+SRCDIR=/opt/src
+TECDIR=$SRCDIR/tecgraf
+
+set_tecgraf_profile "$2"
+set_packages_param
+
+case "$1" in
+    install_libs)
+        install_libs 
+    ;;
+    uninstall_libs)
+        uninstall_libs
+    ;;
+    uninstall)
         uninstall_tecgraf
-    fi
-    test_tecgraf
-else
-    case "$1" in
-        install_libs)
-            install_libs 
-        ;;
-        uninstall_libs)
-            uninstall_libs
-        ;;
-        *)
-            echo "algo fallo!"
+        test_tecgraf
+    ;;
+    '' | install_tecgraf)
+        install_tecgraf
+        test_tecgraf
+        [[ "$fail_test" == "Yes" ]] && exit 1
+    ;;
+    luatest)
+        test_tecgraf
+        [[ "$fail_test" == "Yes" ]] && exit 1
+    ;;
+    *)
+        echo "ERROR: parametro desconocido '$1'"
         exit 1
-        ;;
-    esac
-fi
+esac
 
 exit 0
 
