mejoras

diff --git a/varios/bibliohack-desktop b/varios/bibliohack-desktop
--- a/varios/bibliohack-desktop
+++ b/varios/bibliohack-desktop
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+[[ "$1" != "" ]] && BIBLIOHACK_ORIG="$1" || error_msg "error: BIBLIOHACK_ORIG='$BIBLIOHACK_ORIG'"
+
 function check_and_remove_pkg() {
 
   for pkg in "$@"; do
@@ -26,6 +28,50 @@ function check_and_install_pkg() {
       fi
    done
    return 0
+}
+
+dpkg_install() {
+	[[ ! -z "$1" ]] && ORIGDPKG="$1" || return 1
+	current_folder="$PWD"
+	cd "$ORIGDPKG"
+	sudo dpkg -iEG *.deb || {
+		>&2 echo "ERROR al instalar con dpkg"
+		cd "$current_folder"
+		return 1
+	}
+	cd "$current_folder"
+	return 0
+}
+
+cp_and_untar() {
+	# ORIGPATH: path/to/file.tar.gz; DESTDIR: path/to/dir; TARBASECUSTOM: alt tar dir basename (opt)
+	[[ ! -z "$1" ]] && ORIGPATH="$1" || return 1
+	[[ ! -z "$2" ]] && DESTDIR="$2" || return 1
+	[[ ! -z "$3" ]] && TARBASECUSTOM="$3"
+	[[ -f "$ORIGPATH" ]] || return 1
+	[[ -d "$DESTDIR" ]] || return 1
+
+	current="$PWD"
+   cd "$DESTDIR"
+	if tar -tf "$ORIGPATH" >/dev/null 2>&1; then
+		cp "$ORIGPATH" "$DESTDIR" | exit 1
+		TARFILE=`basename "$ORIGPATH"`
+		TARBASE=`tar -tf "$TARFILE" | sort | head -1`
+		if [[ -z "$TARBASECUSTOM" ]]; then
+			tar xf "$TARFILE"
+			[[ -d "$TARBASE" ]] && ret=0 || ret=1
+			cd "$current"
+			return $ret
+		else
+			mkdir "$TARBASECUSTOM" || exit 1
+			tar xf "$TARFILE" -C "$TARBASECUSTOM" --strip-components=1 && ret=0 || ret=1
+			cd "$current"
+			return $ret
+		fi
+	else
+		cd "$current"
+		return 1
+	fi
 }
 
 
@@ -65,28 +111,91 @@ if [ "$CURRENT_USER" == "root" ]
   exit 1
 fi
 
-# instalacion de entorno de escritorio
+# ==================== instalacion de entorno de escritorio ============
 
-# sudo service gdm3 stop
+GNOMEBOOKMARKS_FILE="/home/bibliohack/.config/gtk-3.0/bookmarks"
 
-# cargar dpkg del usb!!
+GNOMEBOOKMARKS_CONTENT=$(cat <<EOF
 
-CONTENT="[Seat:*]
+file:///home/bibliohack/Archivo
+file:///home/bibliohack/Descargas
+
+EOF
+)
+
+LIGHTDM_CONF_FILE="/etc/lightdm/lightdm.conf"
+
+LIGHTDM_CONF_CONTENT==$(cat <<EOF
+[Seat:*]
 greeter-session=sleck-greeter
-"
 
-sudo echo $CONTENT > /etc/lightdm/lightdm.conf
+EOF
+)
 
-sudo apt-get remove gdm3
+GNOMEPANELS_FILE="/usr/share/gnome-panel/panel-default-layout.layout"
+
+GNOMEPANELS__CONTENT=$(cat <<EOF
+
+[Toplevel bottom-panel]
+expand=true
+orientation=bottom
+size=24
+y-bottom=0
+
+[Object menu-bar]
+object-iid=PanelInternalFactory::MenuBar
+toplevel-id=bottom-panel
+pack-index=0
+
+[Object window-list]
+object-iid=WnckletFactory::WindowListApplet
+toplevel-id=bottom-panel
+pack-index=1
+
+[Object indicators]
+object-iid=IndicatorAppletCompleteFactory::IndicatorAppletComplete
+toplevel-id=bottom-panel
+pack-type=end
+pack-index=0
+
+[Object workspace-switcher]
+object-iid=WnckletFactory::WorkspaceSwitcherApplet
+toplevel-id=bottom-panel
+pack-type=end
+pack-index=1
+
+EOF
+)
+
+
+sudo systemctl stop gdm3
+
+# instalar lightdm gnome-session-flashback slick-greeter lightdm-settings
+dpkg_install "$BIBLIOHACK_ORIG/deb/bibliohack-desktop"
+
+check_and_remove_pkg 'ubuntu-session' 'gdm3' || { echo "error!"; exit 1; }
+
+sudo echo $LIGHTDM_CONF_CONTENT > "$LIGHTDM_CONF_FILE" || exit 1
 
 sudo dpkg-reconfigure lightdm
 
+# varios desktop config
+
+# que deje de aparecer el popup de actualizaciones de software
+gsettings set com.ubuntu.update-notifier no-show-notifications true || exit 1
+
+# desinstalar tambien unattended-upgrades:
+sudo apt-get remove unattended-upgrades || exit 1
+
+# que el explorador de archivos muestre rutas que se puedan copiar:
+gsettings set org.gnome.nautilus.preferences always-use-location-entry true || exit 1
+
+# Eliminar bookmarks por defecto y agregar "Archivo"
+sudo echo $GNOMEBOOKMARKS_CONTENT > "$GNOMEBOOKMARKS_FILE" || exit 1
+
+
 # #check_and_install_pkg 'lightdm' 'gnome-session-flashback' || { echo "error!"; return 1; }
-# #slick-greeter lightdm-settings
-# check_and_remove_pkg 'ubuntu-session' 'gdm3' || { echo "error!"; return 1; }
 
-
-# /etc/lightdm/slick-greeter.conf
 # ? gnome-tweaks
 
 # arc-theme
@@ -94,19 +203,19 @@ sudo dpkg-reconfigure lightdm
 # dconf-tools
 # gnome-tweaks
 
-# que el explorador de archivos muestre rutas que se puedan copiar:
-# gsettings set org.gnome.nautilus.preferences always-use-location-entry true
-
 # solucionar el problema del nuevo comporatmiento del explorador de archivos
 # (busqueda general cuando se tipea, en vez de ir a los archivso listados)
 # https://askubuntu.com/questions/275883/traditional-search-as-you-type-on-newer-nautilus-versions
 # https://askubuntu.com/questions/1037732/type-ahead-search-using-nautilus-on-ubuntu-18-04
 
-# que deje de aparecer el popup de actualizaciones de software
-# gsettings set com.ubuntu.update-notifier no-show-notifications true
 
-# desinstalar tambien unattended-upgrades:
-# sudo apt-get remove unattended-upgrades 
+## NOTA
+## Para eliminar las carpetas personales
+#     cd ~/.config
+#     cp /etc/xdg/user-dirs.conf .
+#     # cambiar la linea enabled=True por enabled=False
+#     # modificar ~/.config/user-dirs.dirs
+
 
 # telegram
 
