avances instalador desktop

diff --git a/varios/bibliohack-desktop b/varios/bibliohack-desktop
--- a/varios/bibliohack-desktop
+++ b/varios/bibliohack-desktop
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-[[ "$1" != "" ]] && BIBLIOHACK_ORIG="$1" || error_msg "error: BIBLIOHACK_ORIG='$BIBLIOHACK_ORIG'"
+[[ "$1" != "" ]] && BIBLIOHACK_ORIG="$1" || echo "error: BIBLIOHACK_ORIG='$BIBLIOHACK_ORIG'"
+BIBLIOHACK_DIR=/opt/bibliohack
 
 function check_and_remove_pkg() {
 
@@ -116,12 +117,12 @@ fi
 GNOMEBOOKMARKS_FILE="/home/bibliohack/.config/gtk-3.0/bookmarks"
 
 GNOMEBOOKMARKS_CONTENT=$(cat <<EOF
-
 file:///home/bibliohack/Archivo
 file:///home/bibliohack/Descargas
 
 EOF
 )
+
 
 LIGHTDM_CONF_FILE="/etc/lightdm/lightdm.conf"
 
@@ -134,8 +135,7 @@ EOF
 
 GNOMEPANELS_FILE="/usr/share/gnome-panel/panel-default-layout.layout"
 
-GNOMEPANELS__CONTENT=$(cat <<EOF
-
+GNOMEPANELS_CONTENT=$(cat <<EOF
 [Toplevel bottom-panel]
 expand=true
 orientation=bottom
@@ -152,14 +152,14 @@ object-iid=WnckletFactory::WindowListApplet
 toplevel-id=bottom-panel
 pack-index=1
 
-[Object indicators]
-object-iid=IndicatorAppletCompleteFactory::IndicatorAppletComplete
+[Object multi-load-applet]
+object-iid=MultiLoadAppletFactory::MultiLoadApplet
 toplevel-id=bottom-panel
 pack-type=end
 pack-index=0
 
-[Object workspace-switcher]
-object-iid=WnckletFactory::WorkspaceSwitcherApplet
+[Object indicators]
+object-iid=IndicatorAppletCompleteFactory::IndicatorAppletComplete
 toplevel-id=bottom-panel
 pack-type=end
 pack-index=1
@@ -167,68 +167,190 @@ pack-index=1
 EOF
 )
 
+echo "Deteniendo Gdm3"
+sudo systemctl stop gdm3 && echo "OK" || exit 1
 
-sudo systemctl stop gdm3
+echo "Instalando paquetes"
+# #check_and_install_pkg 'lightdm' 'gnome-session-flashback' 'slick-greeter' 'lightdm-settings' 'arc-theme' 'tango-icon-theme' || { echo "error!"; return 1; }
 
-# instalar lightdm gnome-session-flashback slick-greeter lightdm-settings
-# #check_and_install_pkg 'lightdm' 'gnome-session-flashback' 'slick-greeter' 'lightdm-settings' 'arc-theme' || { echo "error!"; return 1; }
-dpkg_install "$BIBLIOHACK_ORIG/deb/bibliohack-desktop"
+dpkg_install "$BIBLIOHACK_ORIG/deb/bibliohack-desktop" && echo "OK" || exit 1
 
-check_and_remove_pkg 'ubuntu-session' 'gdm3' || { echo "error!"; exit 1; }
+echo "Eliminando gdm3"
+check_and_remove_pkg 'ubuntu-session' 'gdm3' && echo "OK" || { echo "error!"; exit 1; }
 
-sudo echo $LIGHTDM_CONF_CONTENT > "$LIGHTDM_CONF_FILE" || exit 1
+echo "Creado archivo de configuracion lightdm greeter-session"
+echo "$LIGHTDM_CONF_CONTENT" | sudo tee "$LIGHTDM_CONF_FILE" && echo "OK" || exit 1
 
-sudo dpkg-reconfigure lightdm
+echo "Configurando lightdm"
+sudo dpkg-reconfigure lightdm && echo "OK" || exit 1
 
-# varios desktop config
+# Configuraciones del escritorio
 
-# que deje de aparecer el popup de actualizaciones de software
-gsettings set com.ubuntu.update-notifier no-show-notifications true || exit 1
+echo "Customizar panel por defecto de Gnome"
+echo "$GNOMEPANELS_CONTENT" | sudo tee "$GNOMEPANELS_FILE" && echo "OK" || exit 1
 
-# desinstalar tambien unattended-upgrades:
-sudo apt-get remove unattended-upgrades || exit 1
+echo "Eliminar bookmarks por defecto y agregar 'Archivo'"
+echo "$GNOMEBOOKMARKS_CONTENT" > "$GNOMEBOOKMARKS_FILE" && echo "OK" || exit 1
 
-# que el explorador de archivos muestre rutas que se puedan copiar:
-gsettings set org.gnome.nautilus.preferences always-use-location-entry true || exit 1
+echo "Deshabilitar popup de actualizaciones de software"
+gsettings set com.ubuntu.update-notifier no-show-notifications true && echo "OK" || exit 1
 
-# Eliminar bookmarks por defecto y agregar "Archivo"
-sudo echo $GNOMEBOOKMARKS_CONTENT > "$GNOMEBOOKMARKS_FILE" || exit 1
+echo "Desinstalar unattended-upgrades"
+sudo apt-get remove unattended-upgrades && echo "OK" || exit 1
+
+echo "Explorador de archivos muestra rutas que se pueden copiar"
+gsettings set org.gnome.nautilus.preferences always-use-location-entry true && echo "OK" || exit 1
+
+echo "La terminal no muestra menu"
+gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false && echo "OK" || exit 1
+
+echo "Dejar solo un area de trabajo"
+gsettings set org.gnome.desktop.wm.preferences num-workspaces 1 && echo "OK" || exit 1
+
+echo "Selecionar Arc-theme"
+gsettings get org.gnome.desktop.interface gtk-theme 'Arc' && echo "OK" || exit 1
+
+# Bibliohack
+
+FIREFOXPREF_FILE="/etc/firefox/syspref.js"
+
+FIREFOXPREF_CONTENT=$(cat <<EOF
+pref('browser.startup.homepage', "http://foro.bibliohack.org");
+
+EOF
+)
+
+MENUBIBLIOHACK_FILE="/etc/xdg/menus/applications-merged/bibliohack.menu"
+
+MENUBIBLIOHACK_CONTENT=$(cat <<EOF
+<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"
+ "http://www.freedesktop.org/standards/menu-spec/1.0/menu.dtd">
+<Menu>
+  <Name>Applications</Name>
+  <Menu>
+    <Name>Bibliohack</Name>
+    <Directory>Bibliohack.directory</Directory>
+    <Include>
+        <Category>Bibliohack</Category>
+    </Include>
+  </Menu> <!-- End hamradio -->
+</Menu>
+
+EOF
+)
+
+
+DIRBIBLIOHACK_FILE="/usr/share/desktop-directories/Bibliohack.directory"
+
+DIRBIBLIOHACK_CONTENT=$(cat <<EOF
+[Desktop Entry]
+Name=Bibliohack
+Comment=Bibliohack menu
+Icon=applications-multimedia
+Type=Directory
+X-Ubuntu-Gettext-Domain=gnome-menus-3.0
+
+EOF
+)
+
+APPDALCLICK_FILE="/usr/share/applications/dalclick.desktop"
+
+APPDALCLICK_CONTENT=$(cat <<EOF
+[Desktop Entry]
+Version=1.0
+Type=Application
+Terminal=true
+Categories=GNOME;Bibliohack;
+Icon[es_AR]=/usr/share/icons/Tango/scalable/devices/camera.svg
+Exec=${BIBLIOHACK_DIR}/dalclick/dalclick
+Name[es_AR]=DALclick
+Name=dalclick
+Icon=/usr/share/icons/Tango/scalable/devices/camera.svg
+Comment[es_AR]=Gestor de Captura
+Comment=Gestor de Captura
+
+EOF
+)
+
+APPDALPROC_FILE="/usr/share/applications/dalproc.desktop"
+
+APPDALPROC_CONTENT=$(cat <<EOF
+[Desktop Entry]
+Version=1.0
+Type=Application
+Terminal=true
+Categories=GNOME;Bibliohack;
+Icon[es_AR]=/usr/share/icons/Tango/scalable/categories/applications-system.svg
+Exec=${BIBLIOHACK_DIR}/dalclick/ppm/ppm_daemon.sh
+Name[es_AR]=DALproc
+Name=DALproc
+Icon=/usr/share/icons/Tango/scalable/categories/applications-system.svg
+Comment[es_AR]=Gestor de Postproceso
+Comment=Gestor de Postproceso
+
+EOF
+)
+
+if [[ -f "${BIBLIOHACK_DIR}/dalclick/dalclick" ]]
+  then
+	echo "Creando menu bibliohack"
+	sudo mkdir "/etc/xdg/menus/applications-merged" || exit 1
+	echo "$MENUBIBLIOHACK_CONTENT" | sudo tee "$MENUBIBLIOHACK_FILE" && echo "OK" || exit 1
+
+	echo "Creando directory bibliohack"
+	echo "$DIRBIBLIOHACK_CONTENT" | sudo tee "$DIRBIBLIOHACK_FILE" && echo "OK" || exit 1
+
+	echo "Creando entrada dalclick desktop"
+	echo "$APPDALCLICK_CONTENT" | sudo tee "$APPDALCLICK_FILE" && echo "OK" || exit 1
+
+	echo "Creando entrada dalproc desktop"
+	echo "$APPDALPROC_CONTENT" | sudo tee "$APPDALPROC_FILE" && echo "OK" || exit 1
+
+else
+	echo "No se instalan entradas al menu de Bibliohack porque no está instalado!"
+fi
+
+echo "Página de inicio de Firefox"
+echo "$FIREFOXPREF_CONTENT" | sudo tee -a "$FIREFOXPREF_FILE" && echo "OK" || exit 1
+
+# no seleccionamos Tango icons para el escritorio porque no quedan bien en indicator-applet
+# gsettings set org.gnome.desktop.interface icon-theme 'Tango'
+
 
 ## https://askubuntu.com/questions/1091972/how-do-i-create-app-folders-in-the-gnome-application-menu
 ## https://developer.gnome.org/integration-guide/stable/desktop-files.html.en
 ## https://askubuntu.com/questions/495938/script-adding-launchers-to-the-top-gnome-panel%20 (!) panel
 ## https://developer.gnome.org/integration-guide/stable/desktop-files.html.en
+# gsettings set org.gnome.desktop.app-folders folder-children "['Utilities', 'Sundry', 'YaST', 'Bibliohack']"
+# gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Bibliohack/ apps "['dalclick.desktop', 'dalproc.desktop']"
+# gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Bibliohack/ name 'Bibliohack'
 
-gsettings set org.gnome.desktop.app-folders folder-children "['Bibliohack']"
-
-gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Bibliohack/ apps "['dalclick.desktop', 'dalproc.desktop']"
-
-gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Bibliohack/ name 'Bibliohack'
-
-# ? gnome-tweaks
-
-# arc-theme
-
-# dconf-tools
-# gnome-tweaks
 
 # solucionar el problema del nuevo comporatmiento del explorador de archivos
 # (busqueda general cuando se tipea, en vez de ir a los archivso listados)
 # https://askubuntu.com/questions/275883/traditional-search-as-you-type-on-newer-nautilus-versions
 # https://askubuntu.com/questions/1037732/type-ahead-search-using-nautilus-on-ubuntu-18-04
+# ojo: implica cargar el paquete de nautilus desde otro repo!
 
+# Eliminar las carpetas personales y no solo los shortcuts
+#   cd ~/.config
+#   cp /etc/xdg/user-dirs.conf .
+#   # cambiar la linea enabled=True por enabled=False
+#   # modificar ~/.config/user-dirs.dirs
 
-## NOTA
-## Para eliminar las carpetas personales
-#     cd ~/.config
-#     cp /etc/xdg/user-dirs.conf .
-#     # cambiar la linea enabled=True por enabled=False
-#     # modificar ~/.config/user-dirs.dirs
+# === extra video audio codecs ====
 
+# sudo apt install gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly 
+
+# instaladores que necesitan conexion:
+# sudo apt install libdvdnav4 libdvdread4 libdvd-pkg
+# sudo apt install ubuntu-restricted-extras
 
 # telegram
 
-sudo apt-get install -y telegram-desktop
+echo "Instalando Telegram"
+#sudo apt-get install -y telegram-desktop
+dpkg_install "$BIBLIOHACK_ORIG/deb/telegram" && echo "OK" || exit 1
 
 telegram_desktop_entry="[Desktop Entry]
 Type=Application
@@ -247,8 +369,9 @@ if [[ ! -d "$autostart_path" ]]
  then
    mkdir "$autostart_path" || { echo "error!"; return 1; }
 fi
-
-echo "$telegram_desktop_entry" > "$autostart_path/telegram-desktop.desktop" || { echo "error!"; return 1; }
+if [[ ! -f "$autostart_path/telegram-desktop.desktop" ]]
+	echo "$telegram_desktop_entry" > "$autostart_path/telegram-desktop.desktop" || { echo "error!"; return 1; }
+fi
 
 # micro
 
@@ -258,25 +381,30 @@ echo "$telegram_desktop_entry" > "$autostart_path/telegram-desktop.desktop" || {
    echo "micro installed"
 }
 
-# keybase
+# # keybase
 
-sudo apt-get -y install gconf-service gconf-service-backend gconf2-common libappindicator1 || { echo "error!"; return 1; }
+# sudo apt-get -y install gconf-service gconf-service-backend gconf2-common libappindicator1 || { echo "error!"; return 1; }
 
-cd /opt || { echo "error!"; return 1; }
+# cd /opt || { echo "error!"; return 1; }
 
-if [ "$ARCH" == "x86_64" ]
- then
-   sudo curl -O https://prerelease.keybase.io/keybase_amd64.deb
-elif [ "$ARCH" == "i386" ] || [ "$ARCH" == "i686" ]
-   sudo curl -O https://prerelease.keybase.io/keybase_i386.deb
-fi 
+# if [ "$ARCH" == "x86_64" ]
+#  then
+#    sudo curl -O https://prerelease.keybase.io/keybase_amd64.deb
+# elif [ "$ARCH" == "i386" ] || [ "$ARCH" == "i686" ]
+#    sudo curl -O https://prerelease.keybase.io/keybase_i386.deb
+# fi 
 
-if [[ -f "keybase_amd64.deb" ]]
-  then
-   sudo dpkg -i keybase_amd64.deb && sudo apt-get install -f 
-   #run_keybase
-   echo "OK: keybase instalado!"
-   keybase signup
-else
-   echo "error: keybase no instalado"
-fi
+# if [[ -f "keybase_amd64.deb" ]]
+#   then
+#    sudo dpkg -i keybase_amd64.deb && sudo apt-get install -f 
+#    #run_keybase
+#    echo "OK: keybase instalado!"
+#    keybase signup
+# else
+#    echo "error: keybase no instalado"
+# fi
+
+# iniciando lightdm
+sudo systemctl start lightdm
+
+exit 0
